### ISSUE TITLE
Major lag on every new world

### ISSUE THREAD

**Issue by Priderino** [An-Sar/PrimalCore#209]
Everytime I create a new world, the world generates normally, but after a few minutes it starts to lag a lot, eventually leading to Minecraft stopping responding.

https://paste.ee/p/OPsLu

**Comment by alxcool** [comment]
Hello! Sorry to put negative assumptions on the game, but ... Does anyone other than me have similar problems? : cascading world gen, who spam the latest.log; in the same dimensions or a similar one as the nether?
PrimalCore-1.12.2-0.6.56
Insomniakitten + VoidCraft-1.12-0.26.10

I started to integrate some new mods recently, and in the void dimension, cineris cilium is generated on chunk creation. This generation is not a problem. Nevertheless, the console displays the error mentioned above.

Note: I take advantage of this topic because I think it's a similar problem to mine, see the same.

**Comment by An-Sar** [comment]
https://github.com/An-Sar/PrimalCore/issues/110

**Comment by Normal69** [comment]
Do not think it's a placebo effect.
On a test server I went over to the nether first time, and cascading generation began dropping tps from 20 down to 3.
I left nether, left the server on overnight, and it generated 2.4GB of nether files.
Definitely a problem.

Thank you for lookin over it, and please tell us how did you've fixed it before closing. ;)

**Comment by An-Sar** [comment]
follow https://github.com/An-Sar/PrimalCore/issues/110 for updated info, thanks to Thiakil next release should include a fix
