### ISSUE TITLE
[Suggestion] Cross-Mod Compatibility For Lighting The Sariras/Hibachi

### ISSUE THREAD

**Issue by inkdear** [An-Sar/PrimalCore#298]
Just wanted to suggest making the Sariras (and hibachi, though less important since you can generally assume access to flint & steel at that point) lightable using firestarters from other mods, namely Primal Tech's fire sticks and Charcoal Pit's fire starter. Off the top of my head I can also think of Realistic Torches' matchbox, but I haven't had that mod in my game for a while so I can't remember if it's a true firestarter or not.

Charcoal Pit's Bloomery is capable of 'absorbing' fires set in front of the hatch and using that to light itself, thought something like that might provide the broadest compatibility.

**Comment by An-Sar** [comment]
There is a config _Flammability.FIRE_SOURCE_ITEMS_ which allows you to add specific items. i have added the items you mentioned above to the default list. i added special handing for the charcoal pit item since it appears it's meant to be single use and doesn't use normal item damage.

also in the next release (0.6.105) FIRE_SOURCE_ITEMS has been merged with FIRE_SOURCE_BLOCKS into a new single list **_Flammability.FIRE_SOURCES_**
