### ISSUE TITLE
It does not appear to be possible to move or place a dry thatch block

### ISSUE THREAD

**Issue by lookbehindyoo** [An-Sar/PrimalCore#59]
Letting wet thatch dry results in a block which has changed colour to yellow and yields two thatch slabs when broken, but is still listed as wet thatch in The One Probe.  

Once you have slabs, it does not appear to be possible to make a dry thatch block from them, either in world or via some crafting recipe. Is this by design? I dont want to have to build my roof from wet thatch unless really necessary

**Comment by An-Sar** [comment]
you're meant to use the slabs, which can be picked up with a sneak-click. The dry stage of the wet thatch will become wet again if exposed to water which is why the one probe sees it as the same block. 

It appears combining the thatch slabs into a full block has gotten broken, this is a bug and should hopefully be fixed for the next release.

**Comment by An-Sar** [comment]
This should be fixed, does the full slab placement address your issue?

**Comment by An-Sar** [comment]
I believe this has been resolved.
